### ISSUE TITLE
Pressing ESC permanently sets all results to DNF when not using inspection

### ISSUE THREAD

**Issue by dlangevi** [DallasMcNeil/Block-Keeper#1]
In your timerUpdate function you initialize the timerResult to "OK" in startInspection()

However, if not using inspection the value is never setup. This means that when the user presses ESC to invalidate a time during the solve, the timerResult will remain as DNF until the program is restarted.

Easy fix would be to just set timerResult = "OK"  in stopTimer() after calling submitTime()

**Comment by DallasMcNeil** [comment]
Fixed, thank you for picking this up. I committed the change for the next version.
