### ISSUE TITLE
Ability to rename sessions

### ISSUE THREAD

**Issue by coder13** [DallasMcNeil/Block-Keeper#15]
Atm, I have a bunch of sessions imported as "CSTimer Import XY" and want to rename it to what it's supposed to be.

**Comment by DallasMcNeil** [comment]
You can rename sessions by clicking the edit button next to the session select. The dropdown becomes and text box which lets you change the name. This is documented [here](https://dallasmcneil.com/projects/blockkeeper/guide/) under the second part of the interface section.

**Comment by coder13** [comment]
Ooh, subtle. All I did was a quick ctrl+f on our website for "rename" to see if you explained that. Thanks.
