### ISSUE TITLE
[ASK] Can you use Github release system

### ISSUE THREAD

**Issue by OlivierMary** [DallasMcNeil/Block-Keeper#19]
Hi,

First, thank's for all your job 👍 

Can you put your release in github with github release system? 
Just need to TAG + Add files (your zip files)

Cause, media fire links on your site isn't accessible with many proxy, github is generally authorized by all proxy :) And there is no pub on github 👍 

Thank's.

**Comment by DallasMcNeil** [comment]
Thanks! I would be happy too soon but I am unable to for a week as I am on holiday. I’ll set that up once I’m available

**Comment by DallasMcNeil** [comment]
Update on this issue, I'm looking at a long overdue overhaul to the release and update system based around the repo. It might take some time though for me to organise everything as I can be busy.

**Comment by OlivierMary** [comment]
![2018-04-12_14-24-58](https://user-images.githubusercontent.com/4348675/38677096-86c789ca-3e5d-11e8-9bc3-8f1e2cddf793.gif)

**Comment by DallasMcNeil** [comment]
#23
