### ISSUE TITLE
Suggestion and bug with averages

### ISSUE THREAD

**Issue by xsrvmy** [DallasMcNeil/Block-Keeper#20]
Rather than hard-coding the average statistics, can you add an option to choose which averages to show, like how CSTimer does it?

Also, in utilities.js, should line 140 read
```
t = t.slice(Math.ceil(t.length * 0.05), -Math.ceil(t.length * 0.05));
```
? (Original file has `floor` instead of `ceil`)
The number of solves not counted right now for ao50 is wrong.

**Comment by DallasMcNeil** [comment]
By average statistics do you mean the current and best time, Mo3, Ao5, Ao12, ... just above the list of times? Definitely could add an option to customise this. 

I was unaware that the times included were rounded up. 
As an example Ao25, currently it would remove best 1, but it should remove best 2?

**Comment by xsrvmy** [comment]
Yes to both questions.

**Comment by DallasMcNeil** [comment]
Average fix has been committed 
Feature added to Roadmap in wiki
