### ISSUE TITLE
Cannot use "delete" button when only one result is in session

### ISSUE THREAD

**Issue by xsrvmy** [DallasMcNeil/Block-Keeper#21]
Steps to reproduce:
- Create a new event or go to an empty one.
- Add exactly one solve.
- Click on the time.
- Press the "Delete" button on the screen.
Result:
- The solve does not get deleted.
- The solve info window is stuck open, which forces me to restart the exe file.

Note: Ctrl+BSpace still works as expected.

As a sidenote, there should probably be a warning message for deleting solves.

**Comment by DallasMcNeil** [comment]
Addressed in the 'newrelease' branch. Thanks for the feedback. I think a single time confirmation dialog isn't necessary as it is only one time and is an inconvenience in most situations.

**Comment by xsrvmy** [comment]
My reasoning was that the Ctrl-BSpace combo can be hit twice in a row by accident.
