### ISSUE TITLE
4x4 scrambles are random-move instead of random-state

### ISSUE THREAD

**Issue by dancing-jules** [DallasMcNeil/Block-Keeper#29]
I noticed my 4x4 scrambles on Block Keeper look significantly different than on other timers. 

On Reddit someone got a 1-move-F2C scramble: 

https://www.reddit.com/r/Cubers/comments/9n70pv/daily_discussion_thread_oct_11_2018/e7m4enn/

I know TNoodle uses random-state scrambles, so why doesn't Block keeper?

**Comment by DallasMcNeil** [comment]
Scrambles are generated using Scrambo (https://github.com/nickcolley/scrambo) but unknown to me, it doesn't use random state for 4x4x4 and up, based on this comment https://github.com/nickcolley/scrambo/issues/34#issuecomment-367482825. This should be swapped with https://github.com/thewca/tnoodle/tree/master/tnoodlejs. I will do this soon when I find the time.

**Comment by xsrvmy** [comment]
Should there be an option for which one to use? For some people the random state 4x4 scrambler would probably cause lag.

**Comment by DallasMcNeil** [comment]
TNoodle has 4x4x4 Fast scramble generation but 5x5x5 and up will still be slow. I want to try preloading the next scramble and generating them on a seperate thread. That way the next scramble for a solve will always be there and the only delay will be when switching events or scramblers.

**Comment by DallasMcNeil** [comment]
Update: TNoodle is used for all WCA events now. It was difficult to prevent the event loop from pausing while generating the scrambles. However, utilising another Electron render process, Block Keeper stays completely usable while the scramble is generating in another process. 4x4x4 and others generate pretty quickly but some other events like Square-1 and relays are slow (10+ seconds wait). Still needs more work.

**Comment by dancing-jules** [comment]
AFAIK 5x5-7x7 are random move with TNoodle; but 4x4 and Square-1 should be random-state.

**Comment by DallasMcNeil** [comment]
Whichever method they use, it's official now. I'm adding an option to use the fast versions of the 4x4x4 and Square-1 and preloading the next scramble to save time.
