### ISSUE TITLE
Weird ao5 calculations possibly related to DNF's

### ISSUE THREAD

**Issue by HaykTheKhulyan** [DallasMcNeil/Block-Keeper#33]
In the event trends box, I occasionally get ao5 times that are just below the 0.00 horizontal line, which is obviously wrong. I believe it's related to DNF's, but this is just a guess. I've attached a picture of the graph and my block keeper sessions as a CSV. The weird ao5 happened on the 7/27/2019 session and another earlier session, although I'm not sure which one. 

![wierd a05](https://user-images.githubusercontent.com/32423701/62013713-361c5200-b14b-11e9-8962-4f85ee50e3dd.PNG)

**Comment by HaykTheKhulyan** [comment]
[blockkeeper 7-28-2019.txt](https://github.com/DallasMcNeil/Block-Keeper/files/3439625/blockkeeper.7-28-2019.txt)
Here are the sessions, you can change it into a CSV file to make it easier to read. Again, the most recent session with the wierd ao5 is on 7/27/2019

**Comment by HaykTheKhulyan** [comment]
Closed, I submitted a pull request with the fix.

**Comment by DallasMcNeil** [comment]
Nice find, I have merged the fix. Thanks :)
